name: Build main

on:
  workflow_call: { }

jobs:
  format-code:
    name: Format code
    uses: ./.github/workflows/intellij-format.yml

  build:
    needs: format-code
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@main
        with:
          distribution: jetbrains
          java-version: 25

      - name: Give permissions to Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          SKIP_SHOWCASE: true
        run: ./gradlew build -x test