name: Update Changelogs

on:
  workflow_call: { }

jobs:
  update-changelogs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@main
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@main
        with:
          distribution: jetbrains
          java-version: 25

      - name: Install JBang
        run: curl -Ls https://sh.jbang.dev | bash -s - app setup

      - name: Run script
        run: jbang run ./scripts/binaries/UpdateChangelogs.jar