name: Update Changelogs

on:
  workflow_call: { }

jobs:
  update-changelogs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@main
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@main
        with:
          distribution: jetbrains
          java-version: 25

      - name: Run script
        run: java -jar ./scripts/binaries/UpdateChangelogs.jar --commit